class S: #Symbols keywords
    EOF = '{***end-of-file***}'
    NL = '\n'
    WS = ' '
    E = ''
    
    EQUAL = '='
    LESS = '<'
    GREATER = '>'
    COMMA = ','
    SQL = '['
    SQR = ']'
    
    PRINT = 'print'
    
    NUMBER = 'number'
    STRING = 'string'
    BOOL = 'bool'
    
    TRUE = 'true'
    FALSE = 'false'
    
    EVAL = 'eval'
    
    VAR = 'var'
    VAR_REF = '@'
    PLOT = 'plot'
    FOR = 'for'
    IF = 'if'
    COLON = ':'
    FUNCDEF = 'func'
    FUNCCALL = 'call'
    CLASS = 'class'
    ACTION = 'action'
    COMMA = ','
    IS = 'is'
    MAKE = 'make'
    ADD = 'add'
    TO = 'to'
    SEE = 'see'
    OF = 'of'
    SET = 'set'
    ATTRIB = 'attribute'
    TABLE = 'table'